package com.harsha.cloudcomputing.courseservice.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * Announcement
 */
@DynamoDBTable(tableName = "announcements")
public class Announcement {

    private String id;
    private String announcementId;
    private String announcementText;
    private String boardId;

    public Announcement() {

    }

    public Announcement(String announcementId, String announcementText, String boardId) {
        this.announcementId = announcementId;
        this.announcementText = announcementText;
        this.boardId = boardId;
    }

    /**
     * @return the id
     */
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * @return the announcementId
     */
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "AnnouncementBoard-index",
            attributeName = "announcementId")
    public String getAnnouncementId() {
        return announcementId;
    }

    /**
     * @param announcementId the announcementId to set
     */
    public void setAnnouncementId(String announcementId) {
        this.announcementId = announcementId;
    }

    /**
     * @return the announcementText
     */
    @DynamoDBAttribute(attributeName = "announcementText")
    public String getAnnouncementText() {
        return announcementText;
    }

    /**
     * @param announcementText the announcementText to set
     */
    public void setAnnouncementText(String announcementText) {
        this.announcementText = announcementText;
    }

    /**
     * @return the boardId
     */
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "AnnouncementBoard-index",
            attributeName = "boardId")
    public String getBoardId() {
        return boardId;
    }

    /**
     * @param boardId the boardId to set
     */
    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }

    @DynamoDBIgnore
    @Override
    public String toString() {
        return "AnnouncementId = " + getAnnouncementId() + ", boardId = " + getBoardId();
    }

}
