package com.harsha.cloudcomputing.courseservice.datamodel;

import java.util.ArrayList;
import java.util.List;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * Course
 */
@DynamoDBTable(tableName = "courses")
public class Course {

    private String id;
    private String name;
    private String courseId;
    private String taId;
    private String professorId;
    private String program;
    private String boardId;
    private List<String> roster = new ArrayList<>();

    public Course() {

    }

    /**
     * @param courseId    the courseId to set
     * @param name        the name to set
     * @param boardId     the boardId to set
     * @param program     the program to set
     * @param professorId the professorId to set
     * @param taId        the taId to set
     * 
     */
    public Course(String courseId, String name, String boardId, String program, String professorId,
            String taId) {
        this.courseId = courseId;
        this.name = name;
        this.boardId = boardId;
        this.program = program;
        this.taId = taId;
        this.professorId = professorId;
    }

    /**
     * @return the id
     */
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * @return the professor
     */
    @DynamoDBAttribute(attributeName = "professorId")
    public String getProfessorId() {
        return professorId;
    }

    /**
     * @param professorId the professorId to set
     */
    public void setProfessorId(String professorId) {
        this.professorId = professorId;
    }

    /**
     * @return the teachingAssistant
     */
    @DynamoDBAttribute(attributeName = "taId")
    public String getTaId() {
        return taId;
    }

    /**
     * @param taId the taId to set
     */
    public void setTaId(String taId) {
        this.taId = taId;
    }

    /**
     * @return the roster
     */
    @DynamoDBAttribute(attributeName = "roster")
    public List<String> getRoster() {
        return this.roster;
    }

    /**
     * @param roster the roster to set
     */
    public void setRoster(List<String> roster) {
        this.roster = roster;
    }

    /**
     * @return the program
     */
    @DynamoDBAttribute(attributeName = "program")
    public String getProgram() {
        return this.program;
    }

    /**
     * @param program the program to set
     */
    public void setProgram(String program) {
        this.program = program;
    }

    /**
     * @return the courseId
     */
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "courseId-index", attributeName = "courseId")
    public String getCourseId() {
        return courseId;
    }

    /**
     * @param courseId the courseId to set
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    /**
     * @return the name
     */
    @DynamoDBAttribute(attributeName = "name")
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the boardId
     */
    @DynamoDBAttribute(attributeName = "boardId")
    public String getBoardId() {
        return boardId;
    }

    /**
     * @param boardId the boardId to set
     */
    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }

    /**
     * @return the details of Course
     */
    @DynamoDBIgnore
    @Override
    public String toString() {
        return "courseId= " + getCourseId() + ", name= " + getName();
    }
}
