package com.harsha.cloudcomputing.courseservice.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Professor
 */
@DynamoDBTable(tableName = "professors")
public class Professor {

    private String id;
    private String firstName;
    private String lastName;
    private String program;
    private String professorId;
    private String joiningDate;

    public Professor() {

    }

    public Professor(String professorId, String firstName, String lastName, String program,
            String joiningDate) {

        this.professorId = professorId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.program = program;
        this.joiningDate = joiningDate;
    }

    @DynamoDBAttribute(attributeName = "firstName")
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @DynamoDBAttribute(attributeName = "program")
    public String getProgram() {
        return this.program;
    }

    public void setProgram(String program) {
        this.program = program;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "professorId-index",
            attributeName = "professorId")
    public String getProfessorId() {
        return professorId;
    }

    public void setProfessorId(String professorId) {
        this.professorId = professorId;
    }

    @DynamoDBRangeKey(attributeName = "joiningDate")
    public String getJoiningDate() {
        return joiningDate;
    }


    public void setJoiningDate(String joiningDate) {
        this.joiningDate = joiningDate;
    }


    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }


    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "lastName")
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @DynamoDBIgnore
    @Override
    public String toString() {
        return "ProfId=" + getProfessorId() + ", firstName=" + getFirstName() + ", program="
                + getProgram() + ", joiningDate=" + getJoiningDate();
    }
}
